<?php

namespace NinePay\Bidv\Contracts;

class Response
{
	public static $md5 = 'md5';

	public static $rsa = 'rsa';

	private static $responseCode = [
		'000' => 'Giao dịch thành công',
		'001' => 'Hóa đơn đã được thanh toán trước đó',
		'002' => 'Hóa đơn đã hết hạn thanh toán',
		'003' => 'Không tìm thấy thông tin khách hàng',
		'004' => 'Quá thời gian chờ xác thực OTP',
		'005' => 'Sai mã xác thực OTP',
		'006' => 'Dịch vụ không tồn tại',
		'007' => 'Sai chữ ký',
		'008' => 'Từ chối truy cập',
		'009' => 'Chưa định nghĩa client',
		'010' => 'Sai User và Password đăng nhập',
		'011' => 'Trùng dữ liệu hoặc trùng trans_id',
		'012' => 'Dịch vụ chưa đăng ký',
		'013' => 'Thông tin khách hàng đã tồn tại',
		'014' => 'Tài khoản không được phép thanh toán',
		'015' => 'NCC không thực hiện đảo giao dịch',
		'016' => 'NCC thực hiện đảo giao dịch bị lỗi',
		'017' => 'Tên đăng nhập BIDV Online CI không tồn tại',
		'018' => 'Không lấy được thông tin hóa đơn',
		'019' => 'Nhà cung cấp không đúng',
		'020' => 'Dịch vụ không đúng',
		'021' => 'Không tim thấy CMT trên hệ thống corebank',
		'022' => 'Không tim thấy mobile trên hệ thống corebank',
		'025' => 'Khách hàng không có hóa đơn',
		'026' => 'Số tiền thanh toán khác số tiền nợ',
		'027' => 'Số tiền giao dịch vượt quá hạn mức tối đa đối với mỗi giao dịch',
		'028' => 'Tổng số tiền giao dịch vượt quá hạn mức tối đa trong ngày',
		'029' => 'Tổng số lần giao dịch vượt quá hạn mức tối đa trong ngày',
		'030' => 'Mã CN bên bên nhà cung cấp chưa khai báo',
		'031' => 'Thông tin thẻ ghi nợ nội địa (ATM) không tồn tại',
		'032' => 'Thẻ ghi nợ nội địa (ATM) không hoạt động',
		'033' => 'Số tài khoản không tồn tại',
		'034' => 'TK KH bị tạm giữ',
		'035' => 'Tài khoản thanh toán không đủ số dư để thực hiện giao dịch',
		'036' => 'Tài khoản thanh toán không hoạt động',
		'037' => 'Trạng thái đăng ký dịch vụ BIDV Online không hợp lệ',
		'038' => 'Số tiền còn lại trong tài khoản không đủ số dư tối thiểu',
		'039' => 'Tài khoản KH tại NCC đang bị khóa',
		'040' => 'Tên khách hàng không đúng',
		'041' => 'Khách hàng chưa đăng ký dịch vụ tại BIDV hoặc đang không ở trạng thái hoạt động',
		'042' => 'Khách hàng chưa đăng ký dịch vụ tại NCC',
		'043' => 'Dữ liệu NULL',
		'044' => 'Số tiền ko hợp lệ',
		'045' => 'Số tiền âm',
		'046' => 'Thẻ ghi nợ không hoạt động',
		'047' => 'Thẻ ghi nợ không hoạt động',
		'048' => 'Thẻ ghi nợ không hoạt động',
		'049' => 'Số tiền giao dịch nhỏ hơn hạn mức tối thiểu',
		'050' => 'Giao dịch đang chờ xử lý',
		'051' => 'Ngày phát hành không hợp lệ',
		'052' => 'Giao dịch vượt quá hạn mức tối đa bypass OTP trong ngày cho một khách hàng',
		'053' => 'Giao dịch vượt quá hạn mức tối đa bypass OTP trong ngày cho một dịch vụ',
		'054' => 'Quý khách CHƯA đổi mật khẩu DV BIDV Smart Banking lần đầu. Vui lòng đổi mật khẩu lần đầu tại ứng dụng BIDV Smart Banking',
		'055' => 'User hoặc Mật khẩu không đúng',
		'056' => 'Không gạch nợ được hóa đơn',
		'057' => 'Quý khách đang sử dụng BIDV Online gói phi tài chính. Quý khách cần đăng ký BIDV Online gói tài chính để sử dụng dịch vụ.',
		'058' => 'Giao dịch hoàn tiền không thực hiện được do tran_id giao dịch gốc không chính xác hoặc giao dịch gốc không thành công',
		'059' => 'Giao dịch hoàn tiền không thực hiện được do số tiền yêu cầu hoàn lớn hơn số tiền giao dịch gốc',
		'060' => 'Có lỗi trong quá trình xác thực OTP hoặc khách hàng bị khóa OTP tạm thời do nhập sai OTP 5 lần liên tiếp',
		'061' => 'Có lỗi trong quá trình xác thực OTP',
		'062' => 'Không vấn tin được số dư tài khoản',
		'063' => 'Giao dịch không thực hiện được. Vui lòng thực hiện lại sau.',
		'064' => 'Giao dịch lỗi. Quý khách vui lòng kiểm tra số dư tài khoản và liên hệ với TTCSKH BIDV qua số điện thoại 19009247 để được hỗ trợ xử lý.',
		'065' => 'Quý khách chưa đăng ký số điện thoại nhận OTP để thanh toán giao dịch trực tuyến',
		'066' => 'Tài khoản không hợp lệ',
		'067' => 'Quý khách đang sử dụng BIDV Smart Banking gói phi tài chính. Quý khách cần đăng ký BIDV Smart Banking gói tài chính để sử dụng dịch vụ.',
		'068' => 'Quý khách CHƯA đổi mật khẩu DV BIDV Online lần đầu. Vui lòng đổi mật khẩu lần đầu tại BIDV Online',
		'092' => 'Routing Error',
		'096' => 'Giao dịch không thực hiện được. Vui lòng thực hiện lại sau.',
		'097' => 'Giao dịch không thực hiện được. Vui lòng thực hiện lại sau.',
		'098' => 'Loại thẻ thanh toán không hợp lệ',
		'099' => 'Thông tin thanh toán bị thay đổi',
		'100' => 'Giao dịch lỗi. Quý khách vui lòng liên hệ với Nhà cung cấp dịch vụ để được hỗ trợ xử lý.',
		'101' => 'Sai định dạng Message/Không định nghĩa Message',
		'102' => 'Không hỗ trợ loại tiền tệ này',
		'103' => 'Giao dịch không thực hiện được. Vui lòng thực hiện lại sau',
		'104' => 'Giao dịch không thực hiện được. Vui lòng thực hiện lại sau',
		'105' => 'Giao dịch bị hủy',
		'106' => 'Số điện thoại BUNO không trùng số điện thoại BIDV Online',
		'107' => 'Mã ví đã liên kết đúng với user BIDV online xác thực',
		'108' => 'Số CIF đã sử dụng đăng ký BUNO hoặc đang xử lý tại quầy',
		'109' => 'Mã ví đang được xử lý tại quầy BIDV',
		'110' => 'Mã ví đã được liên kết',
		'111' => 'Mã ví chưa liên kết',
		'112' => 'Cần nhập OTP cho giao dịch vượt hạn mức',
		'113' => 'Số tài khoản đã được liên kết với ví điện tử/mã khách hàng khác của Nhà cung cấp. Vui lòng hủy liên kết cũ trước khi tạo liên kết mới.',
		'114' => 'Giao dịch không thực hiện được. Vui lòng thực hiện lại sau.',
	];

	public static function readMessageFromResponseCode($code)
	{
		return (!empty(self::$responseCode[$code])) ? self::$responseCode[$code] : '';
	}
}